"use strict";

(() => {
  const LOCALE_KEY = "dev-mesh-observer.locale";
  const THEME_KEY = "dev-mesh-observer.theme";
  const locales = ["zh-CN", "en"];
  const themes = ["auto", "light", "dark"];

  const messages = {
    "zh-CN": {
      "app.description": "Dev Mesh 多工作区协作观测控制台",
      "brand.home": "Dev Mesh Observer 首页",
      "connection.connecting": "正在连接",
      "connection.refreshing": "正在刷新",
      "connection.collecting": "正在采集",
      "connection.online": "Observer 在线",
      "connection.failed": "连接失败",
      "connection.collectFailed": "采集失败",
      "collector.waiting": "等待采集",
      "collector.collecting": "正在自动采集",
      "collector.collectingWithDelta": "新增 {count} 条 · 正在采集",
      "collector.live": "自动采集 · {seconds} 秒前",
      "collector.liveWithDelta": "新增 {count} 条 · {seconds} 秒前",
      "collector.pending": "{count} 条事件待采集",
      "collector.error": "自动采集失败",
      "collector.disabled": "仅手动采集",
      "preferences.language": "语言",
      "preferences.theme": "显示主题",
      "theme.auto": "跟随系统",
      "theme.light": "亮色",
      "theme.dark": "暗色",
      "hero.eyebrow": "本地协作观测",
      "hero.title1": "看清 Agent 之间",
      "hero.title2": "发生了什么。",
      "hero.copy": "从不可变事件与受限的活跃争用快照还原协作因果链。控制台只写 Observer 数据库，不改变任何源工作区。",
      "toolbar.label": "观察窗口",
      "since.1h": "最近 1 小时",
      "since.24h": "最近 24 小时",
      "since.48h": "最近 48 小时",
      "since.7d": "最近 7 天",
      "since.4w": "最近 4 周",
      "action.refresh": "刷新视图",
      "action.collect": "立即采集",
      "metrics.label": "观察摘要",
      "metrics.workspaces": "工作区",
      "metrics.events": "窗口内事件",
      "metrics.openRuns": "开放 Run",
      "metrics.pendingHandoffs": "Pending Handoff",
      "metrics.issues": "Integrity Issues",
      "metrics.waiting": "等待数据",
      "metrics.issueHint": "采集与不可变性检查",
      "metrics.available": "{count} 个可访问",
      "metrics.active": "{count} 个活跃工作区",
      "metrics.runs": "{closed} 已关闭 / {total} 总计",
      "metrics.handoffs": "{accepted} 已接受 / {offered} 发起",
      "graph.kicker": "项目边界",
      "graph.title": "项目协作",
      "graph.workspace": "项目视图",
      "graph.waiting": "等待图数据",
      "graph.count": "{nodes} 个节点 · {edges} 条关系",
      "graph.truncated": "显示 {visible}/{total} 个节点",
      "graph.empty": "所选项目在当前窗口没有可绘制的协作关系",
      "graph.aria": "Agent 协作因果图",
      "graph.legend": "协作图图例",
      "graph.inspectorKicker": "节点检查器",
      "graph.selectNode": "选择一个节点",
      "graph.selectHint": "点击图中的 Agent、争用、交接或事务查看关联事实。",
      "graph.type.agent": "Agent",
      "graph.type.handoff": "Handoff",
      "graph.type.contention": "Contention",
      "graph.type.transaction": "Transaction",
      "graph.type.commit": "Commit",
      "graph.status.active": "进行中",
      "graph.status.closed": "已结束",
      "graph.status.stalled": "已停滞",
      "graph.status.offered": "待接收",
      "graph.status.accepted": "已接收",
      "graph.status.published": "已发布",
      "graph.status.completed": "已完成",
      "graph.status.enacted": "已执行",
      "graph.status.conflicted": "有冲突",
      "graph.status.paused": "已暂停",
      "graph.status.prepared": "已准备",
      "graph.status.ready": "待发布",
      "graph.status.refreshing": "正在刷新",
      "graph.status.publishing": "正在发布",
      "graph.status.aborted": "已中止",
      "graph.status.observed": "已观察",
      "graph.detail.workspace": "工作区",
      "graph.detail.status": "状态",
      "graph.detail.events": "事件",
      "graph.detail.runs": "Runs",
      "graph.detail.claims": "Claims",
      "graph.detail.paths": "路径",
      "graph.detail.semantic_resources": "语义资源",
      "graph.detail.tasks": "任务",
      "graph.detail.missing_responses": "缺少响应",
      "graph.detail.lease_until": "Lease 截止",
      "graph.detail.recommendation_reason": "路由理由",
      "storyline.legend": "协作脉络图例",
      "storyline.legend.canonical": "当前分支",
      "storyline.legend.session": "会话起点",
      "storyline.legend.work": "动作节点",
      "storyline.legend.inferred": "推断挂接",
      "storyline.legend.unbound": "未关联 Run",
      "storyline.legend.progress": "Run 执行主干",
      "storyline.legend.branch": "临时分支 · 分叉 / 合回",
      "storyline.legend.handoff": "交接 / 重分配",
      "storyline.legend.message": "通知",
      "storyline.legend.waiting": "等待 / 依赖",
      "storyline.legend.diverted": "转做其他工作",
      "storyline.legend.contention": "冲突 / 争用",
      "storyline.legend.hint": "从左到右阅读；悬停看简卡，点击看详情",
      "storyline.aria": "按协作方编号泳道排列的项目协作脉络",
      "storyline.progressAria": "Run 执行主干与动作挂接；点线挂接是受限推断，不表示授权或额外因果关系",
      "storyline.empty": "所选项目在当前窗口没有可整理的协作脉络",
      "storyline.count": "当前片段：{actors} 个相关方 · {nodes} 个节点 · {relations} 条关系",
      "storyline.countWithLatest": "当前片段：{actors} 个相关方 · {nodes} 个节点 · {relations} 条关系 · 片段末次 {time}",
      "storyline.countWithProjectLatest": "当前片段：{actors} 个相关方 · {nodes} 个节点 · {relations} 条关系 · 项目最近 {time}",
      "storyline.demo.task.contract": "重构共享路由契约",
      "storyline.demo.task.feature": "增加 Metrics 路由",
      "storyline.demo.task.tests": "迁移路由集成测试",
      "storyline.demo.scope.contract": "路由契约重构",
      "storyline.demo.scope.feature": "Metrics 路由实现",
      "storyline.demo.scope.tests": "路由测试迁移",
      "storyline.demo.scope.fixtures": "接手契约测试夹具",
      "storyline.demo.scope.branchWork": "在临时分支完成 Metrics 路由",
      "storyline.demo.waiting": "等待新路由契约",
      "storyline.demo.diverted": "转做独立文档",
      "storyline.demo.transaction": "Metrics 临时 Git 事务",
      "storyline.demo.decision": "采用有序临时事务",
      "storyline.demo.base": "契约稳定基点",
      "storyline.demo.checkpoint": "候选已验证",
      "storyline.demo.publish": "事务已发布并合回",
      "storyline.demo.contention": "路由文件发生语义交叉",
      "storyline.demo.handoff": "交接测试夹具",
      "storyline.demo.message.contractReady": "通知契约已稳定",
      "storyline.demo.message.published": "通知事务已发布",
      "storyline.demo.fork": "从稳定基点分叉",
      "storyline.demo.rejoin": "发布并合回当前分支",
      "storyline.focusNote": "窗口内 {owners} 个 owner 标识 / {runs} 个已记录 run / 峰值并发 {peak}；当前展开 {actors} 个相关方",
      "storyline.truncated": "显示最近 {visible}/{total} 个要点",
      "storyline.inspectorKicker": "细节检查器",
      "storyline.selectNode": "先阅读脉络",
      "storyline.selectHint": "需要时点击工作、交叉或检查点，再查看路径与协议事实。",
      "storyline.lane.canonical": "当前分支 {branch}",
      "storyline.lane.system": "Git / 发布",
      "storyline.lane.actor": "协作方 {index}",
      "storyline.laneItems": "{count} 个要点",
      "storyline.laneStarted": "首次记录 {time}",
      "storyline.intersection": "发现工作交叉",
      "storyline.relation.fork": "从当前分支分叉",
      "storyline.relation.rejoin": "合回当前分支",
      "storyline.relation.waiting": "等待依赖",
      "storyline.relation.diverted": "先做其他工作",
      "storyline.relation.handoff": "交接 / 重分配",
      "storyline.relation.message": "通知",
      "storyline.type.session": "Agent 会话",
      "storyline.type.claim": "声明",
      "storyline.type.handoff": "交接",
      "storyline.type.contention": "交叉",
      "storyline.type.decision": "决策",
      "storyline.type.transaction": "临时事务",
      "storyline.type.waiting": "等待",
      "storyline.type.diverted": "转做其他工作",
      "storyline.type.canonical": "当前版本",
      "storyline.type.base": "分叉基点",
      "storyline.type.publish": "合回版本",
      "storyline.type.transaction-checkpoint": "事务检查点",
      "storyline.type.fork": "分叉",
      "storyline.type.rejoin": "合回",
      "storyline.type.message": "通知",
      "storyline.type.reassigned": "事务重分配",
      "storyline.type.waits-for": "等待依赖",
      "storyline.type.blocked": "阻塞依赖",
      "storyline.type.diverts-to": "转做其他工作",
      "storyline.status.proposed": "待确认",
      "storyline.status.rejected": "被拒绝",
      "storyline.status.invalidated": "已失效",
      "storyline.detail.owner": "负责方",
      "storyline.detail.time": "时间",
      "storyline.detail.events": "聚合事件",
      "storyline.detail.runs": "Runs",
      "storyline.detail.scopes": "Scopes",
      "storyline.detail.paths": "路径",
      "storyline.detail.semantic_resources": "语义资源",
      "storyline.detail.event_types": "事件类型",
      "storyline.detail.missing_responses": "缺少响应",
      "storyline.detail.parent_owner": "父 Agent",
      "storyline.detail.source_owner": "交接发起方",
      "storyline.detail.target_owner": "交接接收方",
      "storyline.detail.intent": "修改意图",
      "storyline.detail.outcome": "结果",
      "storyline.detail.summary": "摘要",
      "storyline.detail.recommendation": "建议路由",
      "storyline.detail.recommendation_reason": "建议理由",
      "storyline.detail.coordinator": "协调者",
      "storyline.detail.lease_until": "Lease 截止",
      "storyline.detail.reason": "理由",
      "storyline.detail.decision_revision": "决策版本",
      "storyline.detail.transaction_id": "Transaction ID",
      "storyline.detail.candidate": "候选提交",
      "storyline.detail.request_id": "Request ID",
      "storyline.detail.request_status": "请求状态",
      "storyline.detail.trace_quality": "轨迹质量",
      "storyline.detail.evidence": "关系证据",
      "storyline.detail.actor_owner": "操作方",
      "storyline.detail.work_owner": "工作归属",
      "storyline.detail.alternate_run_id": "替代 Run",
      "storyline.detail.alternate_scope": "替代工作",
      "storyline.detail.base_revision": "分叉基点",
      "storyline.detail.branch": "临时分支",
      "storyline.detail.canonical_branch": "当前分支",
      "storyline.detail.contention_id": "争用 ID",
      "storyline.detail.disposition": "等待处置",
      "storyline.detail.group_id": "事务组",
      "storyline.detail.handoff_id": "交接 ID",
      "storyline.detail.message_id": "消息 ID",
      "storyline.detail.mode": "协调模式",
      "storyline.detail.resume_evidence": "恢复依据",
      "storyline.detail.run_id": "Run ID",
      "storyline.detail.run_binding": "Run 关联",
      "storyline.detail.run_inference": "推断依据",
      "storyline.detail.run_inference_authority": "推断用途",
      "storyline.detail.scope": "事务名 / Scope",
      "storyline.detail.source_events": "原始事件",
      "storyline.detail.steward": "协调者",
      "storyline.detail.work_state_id": "等待状态 ID",
      "storyline.detail.actual_paths": "实际修改路径",
      "storyline.detail.blocked_by_owners": "等待的 Agent",
      "storyline.detail.blocked_by_scopes": "等待的工作",
      "storyline.detail.blocker_refs": "阻塞依据",
      "storyline.detail.conflicts": "冲突",
      "storyline.detail.owners": "相关 Agent",
      "storyline.detail.workspace_id": "工作区 ID",
      "storyline.detail.workspace_root": "工作区目录",
      "storyline.detail.status": "源状态",
      "storyline.detail.stalled": "是否停滞",
      "storyline.detail.coordinator_epoch": "协调轮次",
      "storyline.detail.lease_expired": "Lease 已过期",
      "storyline.detail.created_at": "创建时间",
      "storyline.detail.collected_at": "采集时间",
      "storyline.quality.native": "原生契约",
      "storyline.quality.derived": "精确派生",
      "storyline.quality.legacy-unknown": "旧数据 / 未知",
      "storyline.runBinding.native": "已由协议明确关联",
      "storyline.runBinding.inferred": "按唯一执行窗口推断",
      "storyline.runBinding.unbound": "未关联 Run",
      "storyline.runBinding.mixed": "跨 Run / 无法唯一归属",
      "storyline.run_inference.unique-owner-run-window": "同一 owner 的唯一完整 Run 窗口",
      "storyline.run_inference_authority.presentation-only": "仅用于可视化，不改变协议事实",
      "projectOverview.selector": "项目总览",
      "projectOverview.waiting": "等待项目数据",
      "projectOverview.count": "{projects} 个项目 · {active} 个有活动",
      "projectOverview.crossProjectTitle": "当前没有跨项目协作追踪",
      "projectOverview.crossProjectBody": "这里分别汇总各项目；只有协议记录明确的跨工作区 correlation 后，才会建立项目之间的关系。",
      "projectOverview.empty": "尚未登记可观测项目",
      "projectOverview.openAria": "打开 {project} 的项目协作图",
      "projectOverview.status.unavailable": "不可访问",
      "projectOverview.status.stalled": "有停滞",
      "projectOverview.status.coordinating": "协调中",
      "projectOverview.status.active": "进行中",
      "projectOverview.status.observed": "有活动",
      "projectOverview.status.quiet": "安静",
      "projectOverview.events": "窗口事件",
      "projectOverview.activeRuns": "开放 Runs",
      "projectOverview.pendingHandoffs": "待接 Handoff",
      "projectOverview.contentions": "活跃争用",
      "projectOverview.transactions": "事务",
      "projectOverview.signals": "协作信号",
      "projectOverview.lastActivity": "最近活动 {time}",
      "projectOverview.noActivity": "窗口内无活动",
      "projectOverview.openGraph": "查看项目图 →",
      "analytics.label": "协作诊断",
      "analytics.kicker": "诊断",
      "conflicts.title": "冲突汇总",
      "conflicts.signals": "冲突信号",
      "conflicts.contentions": "争用",
      "conflicts.stalled": "已停滞",
      "conflicts.refresh": "合并冲突",
      "conflicts.blocked": "队列阻塞",
      "conflicts.attention": "需关注",
      "conflicts.hotspots": "冲突相关路径",
      "conflicts.noHotspots": "当前窗口没有路径级冲突证据",
      "conflicts.signalCount": "{count} 次信号",
      "transactions.title": "事务",
      "transactions.observed": "观察到的事务",
      "transactions.published": "已发布",
      "transactions.conflicted": "曾冲突",
      "transactions.aborted": "已中止",
      "transactions.noData": "当前窗口没有 transaction 事件",
      "transaction.status.active": "进行中",
      "transaction.status.paused": "已暂停",
      "transaction.status.prepared": "已准备",
      "transaction.status.ready": "待发布",
      "transaction.status.refreshing": "正在刷新",
      "transaction.status.conflicted": "发生冲突",
      "transaction.status.publishing": "正在发布",
      "transaction.status.published": "已发布",
      "transaction.status.aborted": "已中止",
      "transaction.status.needs-attention": "需要关注",
      "transaction.status.observed": "已观察",
      "protocolUse.title": "协议利用",
      "protocolUse.solo": "疑似单 Agent 协议",
      "protocolUse.collaborative": "观察到协作",
      "protocolUse.lifecycleOnly": "仅生命周期",
      "protocolUse.open": "开放未判定",
      "protocolUse.noSolo": "当前窗口未发现疑似 solo-protocol run",
      "protocolUse.heuristic": "仅判定已结束 run：产生了协议事件，但未观察到并行 run、父子关系、message、handoff、contention 或 transaction。",
      "protocolUse.eventCount": "{count} 个协议事件",
      "catalog.kicker": "目录",
      "catalog.workspaces": "工作区",
      "workspace.add": "添加工作区",
      "workspace.none": "尚未登记工作区，请点击“添加工作区”。",
      "workspace.events": "{count} 条事件",
      "workspace.unknown": "未知工作区",
      "inflight.kicker": "进行中",
      "inflight.title": "正在进行",
      "inflight.openRuns": "开放 Runs",
      "inflight.handoffs": "等待 Handoff",
      "inflight.noRuns": "暂无开放 run",
      "inflight.noHandoffs": "暂无 pending handoff",
      "activity.kicker": "活动",
      "activity.workspace": "工作区",
      "activity.ownership": "所有者",
      "activity.owner": "Agent Owner",
      "activity.pressure": "压力",
      "activity.resource": "语义资源",
      "activity.none": "当前窗口暂无活动",
      "timeline.kicker": "不可变事件流",
      "timeline.title": "协作时间线",
      "filters.workspace": "工作区",
      "filters.event": "事件类型",
      "filters.owner": "Owner",
      "filters.run": "Run ID",
      "filters.allWorkspaces": "全部工作区",
      "filters.allEvents": "全部事件",
      "filters.allOwners": "全部 Owner",
      "filters.apply": "应用",
      "events.waiting": "等待事件",
      "events.none": "当前筛选条件下没有事件。",
      "events.unknown": "未知事件",
      "events.pagination": "协作时间线分页",
      "events.pageSize": "每页",
      "events.previous": "上一页",
      "events.next": "下一页",
      "events.pageSummary": "第 {page} / {pages} 页 · 共 {count} 条",
      "events.newer": "{count} 条新事件 · 回到最新",
      "issues.kicker": "完整性",
      "issues.title": "采集问题",
      "issues.none": "未发现采集或不可变性问题。",
      "footer.pending": "尚未刷新",
      "footer.updated": "更新于 {time}",
      "eventDetail.kicker": "事件详情",
      "eventDetail.title": "事件详情",
      "action.close": "关闭",
      "workspaceDialog.kicker": "允许扫描目录",
      "workspaceDialog.title": "添加工作区",
      "workspaceDialog.path": "工作区或父目录的绝对路径",
      "workspaceDialog.placeholder": "/Users/you/projects/my-workspace",
      "workspaceDialog.help": "添加即允许 Observer 只读扫描该路径下的不可变事件与活跃争用状态。它不会修改源工作区。",
      "workspaceDialog.depth": "向下扫描深度",
      "workspaceDialog.depth0": "仅当前目录",
      "workspaceDialog.depth2": "向下 2 层",
      "workspaceDialog.depth5": "向下 5 层",
      "workspaceDialog.depth10": "向下 10 层",
      "workspaceDialog.registered": "已登记扫描根",
      "workspaceDialog.noRoots": "尚无扫描根",
      "workspaceDialog.cancel": "取消",
      "workspaceDialog.submit": "添加并采集",
      "workspaceDialog.submitting": "正在添加",
      "toast.collectComplete": "采集完成：新增 {count} 条事件",
      "toast.workspaceAdded": "已添加 {count} 个工作区，新增 {events} 条事件",
      "toast.rootAdded": "扫描根已保存，但暂未发现 .agent-coordination/events",
      "time.unknown": "时间未知",
      "noscript": "此控制台需要 JavaScript 才能显示 Observer 数据。"
    },
    en: {
      "app.description": "Dev Mesh multi-workspace coordination observer console",
      "brand.home": "Dev Mesh Observer home",
      "connection.connecting": "Connecting",
      "connection.refreshing": "Refreshing",
      "connection.collecting": "Collecting",
      "connection.online": "Observer online",
      "connection.failed": "Connection failed",
      "connection.collectFailed": "Collection failed",
      "collector.waiting": "Waiting for collection",
      "collector.collecting": "Auto-collecting",
      "collector.collectingWithDelta": "+{count} events · collecting",
      "collector.live": "Auto collect · {seconds}s ago",
      "collector.liveWithDelta": "+{count} events · {seconds}s ago",
      "collector.pending": "{count} events pending",
      "collector.error": "Auto collection failed",
      "collector.disabled": "Manual collection only",
      "preferences.language": "Language",
      "preferences.theme": "Display theme",
      "theme.auto": "System",
      "theme.light": "Light",
      "theme.dark": "Dark",
      "hero.eyebrow": "LOCAL COORDINATION INTELLIGENCE",
      "hero.title1": "See what happens",
      "hero.title2": "between agents.",
      "hero.copy": "Reconstruct collaboration causality from immutable events and bounded active-contention snapshots. The console writes only to its own database and never changes a source workspace.",
      "toolbar.label": "Observation window",
      "since.1h": "Last hour",
      "since.24h": "Last 24 hours",
      "since.48h": "Last 48 hours",
      "since.7d": "Last 7 days",
      "since.4w": "Last 4 weeks",
      "action.refresh": "Refresh view",
      "action.collect": "Collect now",
      "metrics.label": "Observation summary",
      "metrics.workspaces": "Workspaces",
      "metrics.events": "Events in window",
      "metrics.openRuns": "Open runs",
      "metrics.pendingHandoffs": "Pending handoffs",
      "metrics.issues": "Integrity issues",
      "metrics.waiting": "Waiting for data",
      "metrics.issueHint": "Collection and immutability checks",
      "metrics.available": "{count} available",
      "metrics.active": "{count} active workspaces",
      "metrics.runs": "{closed} closed / {total} total",
      "metrics.handoffs": "{accepted} accepted / {offered} offered",
      "graph.kicker": "PROJECT BOUNDARIES",
      "graph.title": "Project collaboration",
      "graph.workspace": "Project view",
      "graph.waiting": "Waiting for graph data",
      "graph.count": "{nodes} nodes · {edges} relations",
      "graph.truncated": "Showing {visible}/{total} nodes",
      "graph.empty": "No collaboration relationships for this project in the selected window",
      "graph.aria": "Agent collaboration causal graph",
      "graph.legend": "Collaboration graph legend",
      "graph.inspectorKicker": "NODE INSPECTOR",
      "graph.selectNode": "Select a node",
      "graph.selectHint": "Choose an agent, contention, handoff, or transaction to inspect its facts.",
      "graph.type.agent": "Agent",
      "graph.type.handoff": "Handoff",
      "graph.type.contention": "Contention",
      "graph.type.transaction": "Transaction",
      "graph.type.commit": "Commit",
      "graph.status.active": "Active",
      "graph.status.closed": "Closed",
      "graph.status.stalled": "Stalled",
      "graph.status.offered": "Offered",
      "graph.status.accepted": "Accepted",
      "graph.status.published": "Published",
      "graph.status.completed": "Completed",
      "graph.status.enacted": "Enacted",
      "graph.status.conflicted": "Conflicted",
      "graph.status.paused": "Paused",
      "graph.status.prepared": "Prepared",
      "graph.status.ready": "Ready",
      "graph.status.refreshing": "Refreshing",
      "graph.status.publishing": "Publishing",
      "graph.status.aborted": "Aborted",
      "graph.status.observed": "Observed",
      "graph.detail.workspace": "Workspace",
      "graph.detail.status": "Status",
      "graph.detail.events": "Events",
      "graph.detail.runs": "Runs",
      "graph.detail.claims": "Claims",
      "graph.detail.paths": "Paths",
      "graph.detail.semantic_resources": "Semantic resources",
      "graph.detail.tasks": "Tasks",
      "graph.detail.missing_responses": "Missing responses",
      "graph.detail.lease_until": "Lease until",
      "graph.detail.recommendation_reason": "Routing reason",
      "storyline.legend": "Collaboration storyline legend",
      "storyline.legend.canonical": "Canonical branch",
      "storyline.legend.session": "Session start",
      "storyline.legend.work": "Action node",
      "storyline.legend.inferred": "Inferred attachment",
      "storyline.legend.unbound": "Unbound to run",
      "storyline.legend.progress": "Run execution spine",
      "storyline.legend.branch": "Temporary branch · fork / rejoin",
      "storyline.legend.handoff": "Handoff / reassignment",
      "storyline.legend.message": "Notification",
      "storyline.legend.waiting": "Wait / dependency",
      "storyline.legend.diverted": "Diverted work",
      "storyline.legend.contention": "Conflict / contention",
      "storyline.legend.hint": "Read left to right; hover for a card, select for detail",
      "storyline.aria": "Project collaboration storyline arranged in numbered actor lanes",
      "storyline.progressAria": "Run execution spines and action attachments; dotted attachments are bounded inferences and imply neither authority nor additional causality",
      "storyline.empty": "No collaboration storyline can be derived for this project in the selected window",
      "storyline.count": "Current episode: {actors} actors · {nodes} nodes · {relations} relations",
      "storyline.countWithLatest": "Current episode: {actors} actors · {nodes} nodes · {relations} relations · episode latest {time}",
      "storyline.countWithProjectLatest": "Current episode: {actors} actors · {nodes} nodes · {relations} relations · project latest {time}",
      "storyline.demo.task.contract": "Refactor the shared routing contract",
      "storyline.demo.task.feature": "Add the metrics route",
      "storyline.demo.task.tests": "Migrate routing integration tests",
      "storyline.demo.scope.contract": "Routing contract refactor",
      "storyline.demo.scope.feature": "Metrics route implementation",
      "storyline.demo.scope.tests": "Routing test migration",
      "storyline.demo.scope.fixtures": "Take over contract test fixtures",
      "storyline.demo.scope.branchWork": "Implement metrics on the temporary branch",
      "storyline.demo.waiting": "Wait for the new routing contract",
      "storyline.demo.diverted": "Divert to independent documentation",
      "storyline.demo.transaction": "Metrics Git microtransaction",
      "storyline.demo.decision": "Use an ordered microtransaction",
      "storyline.demo.base": "Stable contract base",
      "storyline.demo.checkpoint": "Candidate validated",
      "storyline.demo.publish": "Transaction published and rejoined",
      "storyline.demo.contention": "Semantic overlap in the routing file",
      "storyline.demo.handoff": "Hand off test fixtures",
      "storyline.demo.message.contractReady": "Notify that the contract is stable",
      "storyline.demo.message.published": "Notify that the transaction is published",
      "storyline.demo.fork": "Fork from the stable base",
      "storyline.demo.rejoin": "Publish and rejoin canonical",
      "storyline.focusNote": "Window: {owners} owner labels / {runs} recorded runs / peak concurrency {peak}; showing {actors} related actors",
      "storyline.truncated": "Showing the latest {visible}/{total} moments",
      "storyline.inspectorKicker": "DETAIL INSPECTOR",
      "storyline.selectNode": "Read the storyline first",
      "storyline.selectHint": "Select a work slice, intersection, or checkpoint only when you need its paths and protocol facts.",
      "storyline.lane.canonical": "Canonical {branch}",
      "storyline.lane.system": "Git / publication",
      "storyline.lane.actor": "Actor {index}",
      "storyline.laneItems": "{count} moments",
      "storyline.laneStarted": "first seen {time}",
      "storyline.intersection": "Work intersects",
      "storyline.relation.fork": "Fork from canonical",
      "storyline.relation.rejoin": "Rejoin canonical",
      "storyline.relation.waiting": "Waiting dependency",
      "storyline.relation.diverted": "Diverted to other work",
      "storyline.relation.handoff": "Handoff / reassignment",
      "storyline.relation.message": "Notification",
      "storyline.type.session": "Agent session",
      "storyline.type.claim": "Claim",
      "storyline.type.handoff": "Handoff",
      "storyline.type.contention": "Intersection",
      "storyline.type.decision": "Decision",
      "storyline.type.transaction": "Temporary transaction",
      "storyline.type.waiting": "Waiting",
      "storyline.type.diverted": "Diverted work",
      "storyline.type.canonical": "Canonical revision",
      "storyline.type.base": "Fork base",
      "storyline.type.publish": "Published revision",
      "storyline.type.transaction-checkpoint": "Transaction checkpoint",
      "storyline.type.fork": "Fork",
      "storyline.type.rejoin": "Rejoin",
      "storyline.type.message": "Notification",
      "storyline.type.reassigned": "Transaction reassignment",
      "storyline.type.waits-for": "Waiting dependency",
      "storyline.type.blocked": "Blocked dependency",
      "storyline.type.diverts-to": "Diverted work",
      "storyline.status.proposed": "Proposed",
      "storyline.status.rejected": "Rejected",
      "storyline.status.invalidated": "Invalidated",
      "storyline.detail.owner": "Owner",
      "storyline.detail.time": "Time",
      "storyline.detail.events": "Aggregated events",
      "storyline.detail.runs": "Runs",
      "storyline.detail.scopes": "Scopes",
      "storyline.detail.paths": "Paths",
      "storyline.detail.semantic_resources": "Semantic resources",
      "storyline.detail.event_types": "Event types",
      "storyline.detail.missing_responses": "Missing responses",
      "storyline.detail.parent_owner": "Parent agent",
      "storyline.detail.source_owner": "Handoff source",
      "storyline.detail.target_owner": "Handoff target",
      "storyline.detail.intent": "Intent",
      "storyline.detail.outcome": "Outcome",
      "storyline.detail.summary": "Summary",
      "storyline.detail.recommendation": "Recommended route",
      "storyline.detail.recommendation_reason": "Recommendation reason",
      "storyline.detail.coordinator": "Coordinator",
      "storyline.detail.lease_until": "Lease until",
      "storyline.detail.reason": "Reason",
      "storyline.detail.decision_revision": "Decision revision",
      "storyline.detail.transaction_id": "Transaction ID",
      "storyline.detail.candidate": "Candidate commit",
      "storyline.detail.request_id": "Request ID",
      "storyline.detail.request_status": "Request status",
      "storyline.detail.trace_quality": "Trace quality",
      "storyline.detail.evidence": "Relation evidence",
      "storyline.detail.actor_owner": "Acting owner",
      "storyline.detail.work_owner": "Work owner",
      "storyline.detail.alternate_run_id": "Alternate run",
      "storyline.detail.alternate_scope": "Alternate work",
      "storyline.detail.base_revision": "Fork base",
      "storyline.detail.branch": "Temporary branch",
      "storyline.detail.canonical_branch": "Canonical branch",
      "storyline.detail.contention_id": "Contention ID",
      "storyline.detail.disposition": "Work disposition",
      "storyline.detail.group_id": "Transaction group",
      "storyline.detail.handoff_id": "Handoff ID",
      "storyline.detail.message_id": "Message ID",
      "storyline.detail.mode": "Coordination mode",
      "storyline.detail.resume_evidence": "Resume evidence",
      "storyline.detail.run_id": "Run ID",
      "storyline.detail.run_binding": "Run binding",
      "storyline.detail.run_inference": "Inference evidence",
      "storyline.detail.run_inference_authority": "Inference use",
      "storyline.detail.scope": "Transaction / scope",
      "storyline.detail.source_events": "Source events",
      "storyline.detail.steward": "Steward",
      "storyline.detail.work_state_id": "Work state ID",
      "storyline.detail.actual_paths": "Actual paths",
      "storyline.detail.blocked_by_owners": "Waiting for agents",
      "storyline.detail.blocked_by_scopes": "Waiting for work",
      "storyline.detail.blocker_refs": "Blocking evidence",
      "storyline.detail.conflicts": "Conflicts",
      "storyline.detail.owners": "Related agents",
      "storyline.detail.workspace_id": "Workspace ID",
      "storyline.detail.workspace_root": "Workspace root",
      "storyline.detail.status": "Source status",
      "storyline.detail.stalled": "Stalled",
      "storyline.detail.coordinator_epoch": "Coordinator epoch",
      "storyline.detail.lease_expired": "Lease expired",
      "storyline.detail.created_at": "Created at",
      "storyline.detail.collected_at": "Collected at",
      "storyline.quality.native": "Native contract",
      "storyline.quality.derived": "Exact derivation",
      "storyline.quality.legacy-unknown": "Legacy / unknown",
      "storyline.runBinding.native": "Explicit protocol correlation",
      "storyline.runBinding.inferred": "Inferred from one containing run window",
      "storyline.runBinding.unbound": "No run correlation",
      "storyline.runBinding.mixed": "Multiple runs / no unique binding",
      "storyline.run_inference.unique-owner-run-window": "The only complete run window for this owner",
      "storyline.run_inference_authority.presentation-only": "Visualization only; protocol facts are unchanged",
      "projectOverview.selector": "Project overview",
      "projectOverview.waiting": "Waiting for project data",
      "projectOverview.count": "{projects} projects · {active} active",
      "projectOverview.crossProjectTitle": "Cross-project collaboration is not tracked yet",
      "projectOverview.crossProjectBody": "Projects are summarized separately. Relations will appear between projects only after the protocol records an explicit cross-workspace correlation.",
      "projectOverview.empty": "No observable projects are registered",
      "projectOverview.openAria": "Open the collaboration graph for {project}",
      "projectOverview.status.unavailable": "Unavailable",
      "projectOverview.status.stalled": "Stalled",
      "projectOverview.status.coordinating": "Coordinating",
      "projectOverview.status.active": "Active",
      "projectOverview.status.observed": "Observed",
      "projectOverview.status.quiet": "Quiet",
      "projectOverview.events": "Window events",
      "projectOverview.activeRuns": "Open runs",
      "projectOverview.pendingHandoffs": "Pending handoffs",
      "projectOverview.contentions": "Active contentions",
      "projectOverview.transactions": "Transactions",
      "projectOverview.signals": "Collaboration signals",
      "projectOverview.lastActivity": "Last activity {time}",
      "projectOverview.noActivity": "No activity in window",
      "projectOverview.openGraph": "View project graph →",
      "analytics.label": "Coordination diagnostics",
      "analytics.kicker": "DIAGNOSTICS",
      "conflicts.title": "Conflict summary",
      "conflicts.signals": "Conflict signals",
      "conflicts.contentions": "Contentions",
      "conflicts.stalled": "Stalled",
      "conflicts.refresh": "Merge conflicts",
      "conflicts.blocked": "Queue blocks",
      "conflicts.attention": "Needs attention",
      "conflicts.hotspots": "Conflict-related paths",
      "conflicts.noHotspots": "No path-level conflict evidence in this window",
      "conflicts.signalCount": "{count} signals",
      "transactions.title": "Transactions",
      "transactions.observed": "Observed transactions",
      "transactions.published": "Published",
      "transactions.conflicted": "Ever conflicted",
      "transactions.aborted": "Aborted",
      "transactions.noData": "No transaction events in this window",
      "transaction.status.active": "Active",
      "transaction.status.paused": "Paused",
      "transaction.status.prepared": "Prepared",
      "transaction.status.ready": "Ready",
      "transaction.status.refreshing": "Refreshing",
      "transaction.status.conflicted": "Conflicted",
      "transaction.status.publishing": "Publishing",
      "transaction.status.published": "Published",
      "transaction.status.aborted": "Aborted",
      "transaction.status.needs-attention": "Needs attention",
      "transaction.status.observed": "Observed",
      "protocolUse.title": "Protocol use",
      "protocolUse.solo": "Likely solo protocol",
      "protocolUse.collaborative": "Collaboration observed",
      "protocolUse.lifecycleOnly": "Lifecycle only",
      "protocolUse.open": "Open, unclassified",
      "protocolUse.noSolo": "No likely solo-protocol runs in this window",
      "protocolUse.heuristic": "Closed runs only: protocol events occurred, but no concurrent run, parent-child relation, message, handoff, contention, or transaction was observed.",
      "protocolUse.eventCount": "{count} protocol events",
      "catalog.kicker": "CATALOG",
      "catalog.workspaces": "Workspaces",
      "workspace.add": "Add workspace",
      "workspace.none": "No workspace is registered. Choose “Add workspace” to begin.",
      "workspace.events": "{count} events",
      "workspace.unknown": "Unknown workspace",
      "inflight.kicker": "IN FLIGHT",
      "inflight.title": "In progress",
      "inflight.openRuns": "Open runs",
      "inflight.handoffs": "Pending handoffs",
      "inflight.noRuns": "No open runs",
      "inflight.noHandoffs": "No pending handoffs",
      "activity.kicker": "ACTIVITY",
      "activity.workspace": "Workspace",
      "activity.ownership": "OWNERSHIP",
      "activity.owner": "Agent owner",
      "activity.pressure": "PRESSURE",
      "activity.resource": "Semantic resource",
      "activity.none": "No activity in this window",
      "timeline.kicker": "IMMUTABLE EVENT STREAM",
      "timeline.title": "Coordination timeline",
      "filters.workspace": "Workspace",
      "filters.event": "Event type",
      "filters.owner": "Owner",
      "filters.run": "Run ID",
      "filters.allWorkspaces": "All workspaces",
      "filters.allEvents": "All events",
      "filters.allOwners": "All owners",
      "filters.apply": "Apply",
      "events.waiting": "Waiting for events",
      "events.none": "No events match these filters.",
      "events.unknown": "Unknown event",
      "events.pagination": "Coordination timeline pagination",
      "events.pageSize": "Per page",
      "events.previous": "Previous",
      "events.next": "Next",
      "events.pageSummary": "Page {page} of {pages} · {count} events",
      "events.newer": "{count} new · Back to latest",
      "issues.kicker": "INTEGRITY",
      "issues.title": "Collection issues",
      "issues.none": "No collection or immutability issues found.",
      "footer.pending": "Not refreshed yet",
      "footer.updated": "Updated {time}",
      "eventDetail.kicker": "EVENT DETAIL",
      "eventDetail.title": "Event detail",
      "action.close": "Close",
      "workspaceDialog.kicker": "ALLOWLIST A DIRECTORY",
      "workspaceDialog.title": "Add workspace",
      "workspaceDialog.path": "Absolute path to a workspace or parent directory",
      "workspaceDialog.placeholder": "/Users/you/projects/my-workspace",
      "workspaceDialog.help": "Adding this path allows Observer to read immutable events and bounded active-contention state below it. The source workspace is never modified.",
      "workspaceDialog.depth": "Scan depth",
      "workspaceDialog.depth0": "Current directory only",
      "workspaceDialog.depth2": "2 levels deep",
      "workspaceDialog.depth5": "5 levels deep",
      "workspaceDialog.depth10": "10 levels deep",
      "workspaceDialog.registered": "Registered scan roots",
      "workspaceDialog.noRoots": "No scan roots yet",
      "workspaceDialog.cancel": "Cancel",
      "workspaceDialog.submit": "Add and collect",
      "workspaceDialog.submitting": "Adding",
      "toast.collectComplete": "Collection complete: {count} new events",
      "toast.workspaceAdded": "Added {count} workspaces and {events} new events",
      "toast.rootAdded": "Scan root saved, but no .agent-coordination/events was found yet",
      "time.unknown": "Unknown time",
      "noscript": "JavaScript is required to display Observer data."
    }
  };

  function readPreference(key) {
    try {
      return window.localStorage.getItem(key);
    } catch (_) {
      return null;
    }
  }

  function writePreference(key, value) {
    try {
      window.localStorage.setItem(key, value);
    } catch (_) {
      // Preferences remain session-local when browser storage is unavailable.
    }
  }

  function browserLocale() {
    const candidates = navigator.languages || [navigator.language];
    return candidates.some((value) => String(value).toLowerCase().startsWith("zh"))
      ? "zh-CN"
      : "en";
  }

  const state = {
    locale: locales.includes(readPreference(LOCALE_KEY))
      ? readPreference(LOCALE_KEY)
      : browserLocale(),
    theme: themes.includes(readPreference(THEME_KEY))
      ? readPreference(THEME_KEY)
      : "auto",
  };

  function applyTheme() {
    if (state.theme === "auto") document.documentElement.removeAttribute("data-theme");
    else document.documentElement.dataset.theme = state.theme;
  }

  function t(key, variables = {}) {
    const template = messages[state.locale][key] || messages.en[key] || key;
    return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, name) =>
      Object.prototype.hasOwnProperty.call(variables, name) ? String(variables[name]) : `{${name}}`
    );
  }

  function translateDocument(root = document) {
    root.querySelectorAll("[data-i18n]").forEach((element) => {
      element.textContent = t(element.dataset.i18n);
    });
    ["placeholder", "aria-label", "title"].forEach((attribute) => {
      const marker = `data-i18n-${attribute}`;
      root.querySelectorAll(`[${marker}]`).forEach((element) => {
        element.setAttribute(attribute, t(element.getAttribute(marker)));
      });
    });
    const description = document.querySelector('meta[name="description"]');
    if (description) description.content = t("app.description");
  }

  function setLocale(locale) {
    if (!locales.includes(locale)) return;
    state.locale = locale;
    document.documentElement.lang = locale;
    writePreference(LOCALE_KEY, locale);
    translateDocument();
  }

  function setTheme(theme) {
    if (!themes.includes(theme)) return;
    state.theme = theme;
    writePreference(THEME_KEY, theme);
    applyTheme();
  }

  document.documentElement.lang = state.locale;
  applyTheme();
  window.DevMeshPreferences = {
    get locale() { return state.locale; },
    get theme() { return state.theme; },
    locales,
    themes,
    setLocale,
    setTheme,
    t,
    translateDocument,
  };
})();
